#                     LA FINAL PROJECT CREATIVITY 

## TOPIC: Gaussian Elimination

For our creativity we define some Python functions to solve linear systems. The algorithm is known as Gaussian Elimination, which we will simply refer to as **elimination** .  The idea of elimination is to exchange the system we are given with another system that has the same solution, but is much easier to solve.  To this end we will perform a series of steps called **row operations** which preserve the solution of the system while gradually making the solution more accessible.  There are three such operations we may perform.
1. Exchange the position of two equations.
2. Multiply an equation by any nonzero number.
3. Replace any equation with the sum of itself and a multiple of another equation.



<a id='GE1'></a>
###  1:  Row operations and elimination

Let's look at an example.

$$
\begin{eqnarray*}
x_1 - x_2 + x_3 & = & 3\\
2x_1 + x_2 + 8x_3 & = & 18\\
4x_1 + 2x_2 -3x_3 & = & -2 
\end{eqnarray*}
$$

We swap the first and last equation,

$$
\begin{eqnarray*}
4x_1 + 2x_2 -3x_3 & = & -2 \\
2x_1 + x_2 + 8x_3 & = & 18\\
x_1 - x_2 + x_3 & = & 3
\end{eqnarray*}
$$

or we could multiply the first equation by $5$,

$$
\begin{eqnarray*}
5x_1 - 5x_2 + 5x_3 & = & 15\\
2x_1 + x_2 + 8x_3 & = & 18\\
4x_1 + 2x_2 -3x_3 & = & -2 
\end{eqnarray*}
$$

or we could add 2 times the first equation to the last equation.


$$
\begin{eqnarray*}
x_1 - x_2 + x_3 & = & 3\\
2x_1 + x_2 + 3x_3 & = & 8\\
6x_1 \quad\quad -x_3 & = & 4 
\end{eqnarray*}
$$

The last operation is the most important because it allows us to *eliminate* a variable from one of the equations.  Note that the third equation no longer contains the $x_2$ term.

Augmented Matrix: 

$$
\begin{equation}
\left[ \begin{array}{rrrr} 1 & -1 & 1 & 3 \\ 2 & 1 & 8 & 18 \\ 4 & 2 & -3 & -2 \end{array}\right]
\end{equation}
$$


In [1]:

import numpy as np
A=np.array([[1,-1,1,3],[2,1,8,18],[4,2,-3,-2]])##importing libraries

We will first write a few function so that we can use it again for future calculations.

In [2]:
def RowSwap(A,k,l):

#     A is a NumPy array.  RowSwap will return duplicate array with rows
#     k and l swapped.

    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A
    
    B = np.copy(A).astype('float64')
        
    for j in range(n):
        temp = B[k][j]
        B[k][j] = B[l][j]
        B[l][j] = temp
        
    return B

def RowScale(A,k,scale):
# =============================================================================
#     A is a NumPy array.  ScaleRow will return duplicate array with the
#     entries of row k multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A
    
    B = np.copy(A).astype('float64')

    for j in range(n):
        B[k][j] *= scale
        
    return B

def RowAdd(A,k,l,scale):
# =============================================================================
#     A is a numpy array.  RowSwap will return duplicate array with row
#     l modifed.  The new values will be the old values of row l added to 
#     the values of row k, multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A
    
    B = np.copy(A).astype('float64')
        
    for j in range(n):
        B[l][j] += B[k][j]*scale
        
    return B
    



We now have three new functions called $\texttt{RowSwap}$,$\texttt{RowScale}$,and $\texttt{RowAdd}$. 

In [3]:
B1 = RowSwap(A,0,2)
B2 = RowScale(A,2,0.5)
B3 = RowAdd(A,0,1,2)

In [4]:
print(A)
print('\n')
print(B2)

[[ 1 -1  1  3]
 [ 2  1  8 18]
 [ 4  2 -3 -2]]


[[ 1.  -1.   1.   3. ]
 [ 2.   1.   8.  18. ]
 [ 2.   1.  -1.5 -1. ]]


The goal of elimination is to perform row operations on this array in order to produce a new array with a structure that looks something like this.

$$
\begin{equation}
\left[ \begin{array}{cccc} 1 & * & * & * \\ 0 & 1 & * & * \\ 0 & 0 & 1 & * \end{array}\right]
\end{equation}
$$

*(Note that the * symbols here represent different unknown values that may or may not be 0 or 1.)*

We will carry out the row operations and save our progress as arrays with new names  after each step.  For example, we might name them $\texttt{A1}$, $\texttt{A2}$, $\texttt{A3}$, etc. This way we can check the progress, or go back and make changes to our code if we like.  

In [5]:
## Add -2 times row 0 to row 1
A1 = RowAdd(A,0,1,-2)
print(A1,'\n')

## Add -4 times row 0 to row 2
A2 = RowAdd(A1,0,2,-4)
print(A2,'\n')

## Add -2 times row 1 to row 2
A3 = RowAdd(A2,1,2,-2)
print(A3,'\n')

## Multiply row 1 by 1/3
A4 = RowScale(A3,1,1.0/3)
print(A4,'\n')

## Multiply row 2 by 1/19
A5 = RowScale(A4,2,1.0/-19.)
print(A5)

[[ 1. -1.  1.  3.]
 [ 0.  3.  6. 12.]
 [ 4.  2. -3. -2.]] 

[[  1.  -1.   1.   3.]
 [  0.   3.   6.  12.]
 [  0.   6.  -7. -14.]] 

[[  1.  -1.   1.   3.]
 [  0.   3.   6.  12.]
 [  0.   0. -19. -38.]] 

[[  1.  -1.   1.   3.]
 [  0.   1.   2.   4.]
 [  0.   0. -19. -38.]] 

[[ 1. -1.  1.  3.]
 [ 0.  1.  2.  4.]
 [-0. -0.  1.  2.]]


Now in equation form

$$
\begin{eqnarray*}
x_1 - x_2 + x_3 & = & 3\\
x_2 + 2x_3 & = & 4\\
x_3 & = & 2 
\end{eqnarray*}
$$

After the steps of elimination, we have what is known as a triangular system.  The solution to this system can be found without much effort by working backwards from the last equation.  The last equation tells us that $x_3 = 2$.  If we substitute that value into the second equation, we find that $x_2 = 0$.  Finally, if we substitute these values back into the first equation, we find that $x_1 = 1.$  This process for finding the solution of the triangular system is called **back substitution**.

In [6]:
R = np.random.randint(-8,8,size=(3,4))
print(R)

[[ 0 -6 -8  6]
 [-2 -4 -8  6]
 [-3  1  5 -7]]


###  2: Finding pivots

As critical entries are known as the **pivots**, and their locations in the matrix are called **pivot positions**.  By definition, pivots must be nonzero.  If a zero arises in a pivot position during the elimination steps, we can try to exchange the order of the rows to move a nonzero entry into the pivot position.  Let's first try this for a specific array before trying to write code that will work for a random array.


$$
\begin{eqnarray*}
x_1 - x_2 + x_3 & = & 3\\
2x_1 - 2x_2 + 4x_3 & = & 8\\
3x_1 \quad\quad -9x_3 & = & 0 
\end{eqnarray*}
$$


In [7]:
G=np.array([[1,-1,1,3],[2,-2,4,8],[3,0,-9,0]])
print(G)


[[ 1 -1  1  3]
 [ 2 -2  4  8]
 [ 3  0 -9  0]]


In [8]:
## Add -2 times row 0 to row 1
G1 = RowAdd(G,0,1,-2)
## Add -3 times row 0 to row 2
G2 = RowAdd(G1,0,2,-3)
print(G2)

[[  1.  -1.   1.   3.]
 [  0.   0.   2.   2.]
 [  0.   3. -12.  -9.]]


Now there is a zero in the middle pivot position.  We can swap the middle and last equation in order to carry on the elimination

In [9]:
## Swap rows 1 and 2
G3 = RowSwap(G2,1,2)
## Scale the new row 1 by 1/3
G4 = RowScale(G3,1,1./3)
## Scale the new row 2 by 1/2
G5 = RowScale(G4,2,1./2)
print(G5)

[[ 1. -1.  1.  3.]
 [ 0.  1. -4. -3.]
 [ 0.  0.  1.  1.]]


We write the system again as a familar set of equations.

$$
\begin{eqnarray*}
x_1 - x_2 + x_3 & = & 3\\
x_2 - 4x_3 & = & -3\\
x_3 & = & 1 
\end{eqnarray*}
$$

Applying back substitution, we find that $x_2 = 1$ and $x_1=3$.

It is worth noting that the swapping of rows is only necessary as a matter of organization.  Here is another way that we could have done the elimination and ended up with a system that is just the same.


In [10]:
## Scale row 1 by 1/2
G3_alternative = RowScale(G2,1,1./2)
## Scale row 2 by 1/3
G4_alternative = RowScale(G3_alternative,2,1./3)
print(G4_alternative)

[[ 1. -1.  1.  3.]
 [ 0.  0.  1.  1.]
 [ 0.  1. -4. -3.]]


The array produced represents the same simplified system, with the equations in a different order of course.

$$
\begin{eqnarray*}
x_1 - x_2 + x_3 & = & 3\\
x_3 & = & 1 \\
x_2 - 4x_3 & = & -3
\end{eqnarray*}
$$

The idea of back substitution works just as well with this form of the system, but the organization of the algorithm becomes slightly more complicated.

In this case exchanging the second and third rows does not help since both rows have a zero in the middle entry.  This means that *there is no pivot* in the second column.  Let's scale the rows and look at the result.

### 3)  Nonunique solution

In this final example of elimination, we observe another possible outcome of the process.

$$
\begin{eqnarray*}
x_1 - x_2 + x_3 & = & 3\\
2x_1 - 2x_2 + 4x_3 & = & 8\\
3x_1 -3x_2 +3x_3 & = & 9 
\end{eqnarray*}
$$


In [11]:
F = np.array([[1,-1,1,3],[2,-2,4,8],[1,-1,3,5]])
print(F)

[[ 1 -1  1  3]
 [ 2 -2  4  8]
 [ 1 -1  3  5]]


In [12]:
## Add -2 times row 0 to row 1
F1 = RowAdd(F,0,1,-2)
## Add -3 times row 0 to row 2
F2 = RowAdd(F1,0,2,-1)
print(F2)

[[ 1. -1.  1.  3.]
 [ 0.  0.  2.  2.]
 [ 0.  0.  2.  2.]]


Similar to the previous example, we see that there is no way to bring a nonzero number into the second column of the second row.  In this case though we see that the second and third equations do not contradict each other, but are in fact the same equation.

$$
\begin{eqnarray*}
x_1 - x_2 + x_3 & = & 3\\
2x_3 & = & 2\\
2x_3 & = & 2 
\end{eqnarray*}
$$

Let's do just two more row operations to simplify this system even further.

In [13]:
## Add -1 times row 1 to row 2
F3 = RowAdd(F2,1,2,-1)
## Multiply row 1 by 1/2
F4 = RowScale(F3,1,0.5)
print(F4)

[[ 1. -1.  1.  3.]
 [ 0.  0.  1.  1.]
 [ 0.  0.  0.  0.]]


Since the final equation is true for any values of $x_1$, $x_2$, $x_3$, we see that there are really only two equations to determine the values of the three unknowns.   

$$
\begin{eqnarray*}
x_1 - x_2 + x_3 & = & 3\\
x_3 & = & 1\\
0 & = & 0 
\end{eqnarray*}
$$

Since the middle equation tells us that $x_3=1$, we can plug that value into the first equation using the idea of back substitution.  This leaves us with the single equation $x_1-x_2 = 2$.  This equation, and thus the system as a whole, has an *infinite number of solutions*.